---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность просматривать игры других пользователей
  - Пользователь должен иметь возможность просматривать свою статистику
  - Пользователь должен иметь возможность просматривать статистику других игроков
  - Пользователь должен иметь возможность приглашать других пользователей в игру
  - Пользователь должен иметь возможность менять язык программирования во время игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Чат должен быть доступен только для зарегистрированных пользователей
  - В чате должна присутствовать защита от спама
  - В чате должна присутствовать защита от XXS-атак
